import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from "./AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="text-foreground bg-background">
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
